name: Compilar APK Control de Acceso

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          command: buildozer android debug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: control-acceso-apk
          path: bin/*.apk
